const SET_LOADING_STUDENT = "SET_LOADING_STUDENT";
const SET_LOADING_STUDENT_LIST = "SET_LOADING_STUDENT_LIST";
const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
const CREATE_STUDENT_FAILURE = "CREATE_STUDENT_FAILURE";
const READ_STUDENTS_SUCCESS = "READ_STUDENTS_SUCCESS";
const READ_STUDENTS_FAILURE = "READ_STUDENTS_FAILURE";
const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
const UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE";
const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
const DELETE_STUDENT_FAILURE = "DELETE_STUDENT_FAILURE";
const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
const UPLOAD_PHOTO_FAILURE = "UPLOAD_PHOTO_FAILURE";

const NO_STUDENT_DATA = "NO_STUDENT_DATA";

export default {
    SET_LOADING_STUDENT,
    SET_LOADING_STUDENT_LIST,
    CREATE_STUDENT_SUCCESS,
    CREATE_STUDENT_FAILURE,
    READ_STUDENTS_SUCCESS,
    READ_STUDENTS_FAILURE,
    UPDATE_STUDENT_SUCCESS,
    UPDATE_STUDENT_FAILURE,
    DELETE_STUDENT_SUCCESS,
    DELETE_STUDENT_FAILURE,
    UPLOAD_PHOTO_SUCCESS,
    UPLOAD_PHOTO_FAILURE,
    NO_STUDENT_DATA
}